### ISSUE TITLE
ItemEffect not editable 

### ISSUE THREAD

**Issue by plasticlittle** [plasticlittle/mnm3e#11]
1) Open a power
2) Open Effect tab
3) edit Effect --> Not working

base.js:195 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'actor')
    at ItemSheet3ePower.newChildItem (base.js:195:31)
    at async ItemSheet3ePower.handleListItemEdit (base.js:169:29)
    at async ItemSheet3ePower.onItemListActionHandler (base.js:102:17)

**Comment by plasticlittle** [comment]
const newItem = await this.newChildItem(sourceItem);
            const rawSheet = newItem[0].sheet;
            rawSheet.initializeChildData(sourceItem, this.item, key, list);
            childItem = newItem;
            this._childItems.set(sourceItem, newItem);
